FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
COPY ["Kibol-Alert.csproj", ""]
RUN dotnet restore "./Kibol-Alert.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "Kibol-Alert.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Kibol-Alert.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Kibol-Alert.dll"]